### ISSUE TITLE
update credits for 1.3.0 release

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/area-model-introduction#9]
Opening this issue as a reminder to update credits. 
Aside from yourself, @Luisav1, we will let you know who to add to QA credits.

**Comment by Nancy-Salpepi** [comment]
For QA: Please add Jaron Droder and Nancy Salpepi (in alphabetical order)

**Comment by Luisav1** [comment]
Credits have been updated in main and the 1.3 branches in AMD and AMI. Closing.
